# Generated by Django 4.2.9 on 2024-01-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='images/'),
        ),
    ]
