# Generated by Django 4.2.9 on 2024-01-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='popularity_score',
            field=models.IntegerField(default=0),
        ),
    ]
