# Generated by Django 4.2.9 on 2024-01-07 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
